PORTNAME=	netaddr
PORTVERSION=	1.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	joerg@higgsboson.tk
COMMENT=	A package for manipulating network addresses.

LICENSE=	RUBY

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
